name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup Conan
        uses: conan-io/setup-conan@v1.2.0
        with:
          cache_packages: true

      - name: Setup Poetry
        run: | 
          pip install poetry

      - name: Build
        run: |
          conan build . --build=missing -s compiler.cppstd=20
          poetry install --all-groups

      - name: Test
        run: 
          ctest .

