name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull-requests:
    branches:
      - master

jobs:
  publish:
    name: Publish docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5